from typing import Any, Dict

from dash import dash_table, dcc, html

from frontend.features.discovery_helpers import get_cpu_count
from frontend.ui.dash_constants import (
    BB_BASIS_OPTIONS,
    CHECK_ON,
    DATE_PRESET_OPTIONS,
    ENTRY_BAND_OPTIONS,
    EXCHANGE_OPTIONS,
    EXIT_CHANNEL_OPTIONS,
    EXIT_LEVEL_OPTIONS,
    INLINE_OPTION_STYLE,
    PRESET_DIRECTION_DEFAULT,
    PRESET_DIRECTION_OPTIONS,
    PRESET_LABELS,
    PRESET_OPTIONS,
    RSI_MA_OPTIONS,
    RSI_RELATION_OPTIONS,
    RSI_SMOOTHING_OPTIONS,
    STOP_MODE_OPTIONS,
    TIMEFRAME_OPTIONS,
    TRADE_DIRECTION_OPTIONS,
    TRADE_MODE_OPTIONS,
)
from frontend.ui.dash_utils import _to_checklist


def build_layout(defaults: Dict[str, Any], default_params: Dict[str, Any]) -> html.Div:
    return html.Div(
        [
            dcc.Store(id="store-results"),
            dcc.Store(id="store-params", data=default_params),
            dcc.Store(id="store-last-params"),
            dcc.Store(id="store-dirty", data=False),
            dcc.Store(id="store-selected-trade"),
            dcc.Store(id="store-load-strategy"),
            dcc.Store(id="store-opt-results"),
            dcc.Store(id="store-wf-results"),
            dcc.Store(id="store-leaderboard-selected"),
            dcc.Store(id="store-opt-job"),
            dcc.Store(id="store-disc-job"),
            dcc.Store(id="store-lb-job"),
            dcc.Store(id="store-lb-snapshot"),
            dcc.Store(id="store-pattern-job"),
            dcc.Store(id="store-pattern-rules"),
            dcc.Store(id="store-job-queue"),
            dcc.Store(id="store-job-selected"),
            dcc.Store(id="store-job-detail"),
            dcc.Store(id="store-job-events"),
            dcc.Interval(id="backend-poll", interval=1000, n_intervals=0),
            dcc.Download(id="download-diagnostics"),
            dcc.Download(id="download-optimization"),
            dcc.Download(id="download-walkforward"),
            dcc.Download(id="download-leaderboard"),
            html.Div(id="theme-sink", style={"display": "none"}),
            html.Div(
                [
                    html.H2("BB + KC + RSI Long/Short Strategy", className="page-title"),
                    html.Div(
                        [
                            html.Span("Settings", className="settings-label"),
                            dcc.Checklist(
                                id="theme-toggle",
                                options=[{"label": "Dark mode", "value": CHECK_ON}],
                                value=[],
                                persistence=True,
                                persistence_type="local",
                                className="theme-toggle",
                            ),
                        ],
                        className="header-controls",
                    ),
                ],
                className="header-bar",
            ),
            html.Div(
                [
                    html.Div(
                        [
                            html.Button("Run Backtest", id="run-backtest", n_clicks=0, className="btn-primary"),
                            dcc.Loading(
                                id="loading-backtest",
                                type="default",
                                children=html.Div(id="run-status", style={"marginTop": "8px"}),
                            ),
                            html.Hr(),
                            html.Label("Load Preset"),
                            dcc.Dropdown(
                                id="preset_selector",
                                options=[
                                    {"label": label, "value": value}
                                    for label, value in zip(PRESET_LABELS, PRESET_OPTIONS)
                                ],
                                value="Custom",
                                clearable=False,
                            ),
                            html.Label("Preset direction"),
                            dcc.Dropdown(
                                id="preset_direction",
                                options=PRESET_DIRECTION_OPTIONS,
                                value=PRESET_DIRECTION_DEFAULT,
                                clearable=False,
                            ),
                            html.Div(id="preset-info", style={"marginTop": "6px", "fontSize": "12px"}),
                            html.Div(
                                "Presets only change strategy settings. Data & timeframe stay as-is.",
                                className="helper-text",
                            ),
                            html.Div(
                                [
                                    html.Div(id="preset-reco-text", className="preset-reco-text"),
                                    html.Button(
                                        "Apply Recommended Data",
                                        id="apply-preset-data",
                                        n_clicks=0,
                                        className="btn-secondary",
                                    ),
                                ],
                                id="preset-reco",
                                className="preset-reco",
                                style={"display": "none"},
                            ),
                            html.Hr(),
                            html.Details(
                                [
                                    html.Summary("Data & Timeframe"),
                                    html.Label("Exchange"),
                                    dcc.Dropdown(
                                        id="w_exchange",
                                        options=[{"label": e, "value": e} for e in EXCHANGE_OPTIONS],
                                        value=defaults["w_exchange"],
                                        clearable=False,
                                    ),
                                    html.Label("Symbol"),
                                    dcc.Input(
                                        id="w_symbol",
                                        type="text",
                                        value=defaults["w_symbol"],
                                    ),
                                    html.Label("Timeframe"),
                                    dcc.RadioItems(
                                        id="w_timeframe",
                                        options=[{"label": t, "value": t} for t in TIMEFRAME_OPTIONS],
                                        value=defaults["w_timeframe"],
                                        labelStyle=INLINE_OPTION_STYLE,
                                    ),
                                    html.Label("Lookback window"),
                                    dcc.RadioItems(
                                        id="w_date_preset",
                                        options=DATE_PRESET_OPTIONS,
                                        value=defaults["w_date_preset"],
                                        labelStyle=INLINE_OPTION_STYLE,
                                    ),
                                    html.Label("Custom range (UTC)"),
                                    dcc.DatePickerRange(
                                        id="w_date_range",
                                        start_date=defaults["w_start_date"],
                                        end_date=defaults["w_end_date"],
                                    ),
                                ],
                                open=True,
                                className="section-card",
                            ),
                            html.Details(
                                [
                                    html.Summary("Indicators (BB, KC, RSI)"),
                                    html.Label("BB length"),
                                    dcc.Input(id="w_bb_len", type="number", value=defaults["w_bb_len"], min=5, max=200),
                                    html.Label("BB std dev"),
                                    dcc.Input(id="w_bb_std", type="number", value=defaults["w_bb_std"], min=1.0, max=4.0, step=0.1),
                                    html.Label("BB basis type"),
                                    dcc.Dropdown(
                                        id="w_bb_basis_type",
                                        options=[{"label": o, "value": o} for o in BB_BASIS_OPTIONS],
                                        value=defaults["w_bb_basis_type"],
                                        clearable=False,
                                    ),
                                    html.Label("KC EMA/SMA length (mid)"),
                                    dcc.Input(id="w_kc_ema_len", type="number", value=defaults["w_kc_ema_len"], min=5, max=200),
                                    html.Label("KC ATR length"),
                                    dcc.Input(id="w_kc_atr_len", type="number", value=defaults["w_kc_atr_len"], min=5, max=200),
                                    html.Label("KC ATR multiplier"),
                                    dcc.Input(id="w_kc_mult", type="number", value=defaults["w_kc_mult"], min=0.5, max=5.0, step=0.1),
                                    dcc.Checklist(
                                        id="w_kc_mid_is_ema",
                                        options=[{"label": "KC mid uses EMA", "value": CHECK_ON}],
                                        value=defaults["w_kc_mid_is_ema"],
                                    ),
                                    html.Label("RSI length"),
                                    dcc.Input(id="w_rsi_len_30m", type="number", value=defaults["w_rsi_len_30m"], min=5, max=100),
                                    html.Label("RSI smoothing"),
                                    dcc.Dropdown(
                                        id="w_rsi_smoothing_type",
                                        options=[{"label": o, "value": o} for o in RSI_SMOOTHING_OPTIONS],
                                        value=defaults["w_rsi_smoothing_type"],
                                        clearable=False,
                                    ),
                                    html.Label("RSI MA length"),
                                    dcc.Input(id="w_rsi_ma_len", type="number", value=defaults["w_rsi_ma_len"], min=2, max=100),
                                    html.Label("RSI MA type"),
                                    dcc.Dropdown(
                                        id="w_rsi_ma_type",
                                        options=[{"label": o, "value": o} for o in RSI_MA_OPTIONS],
                                        value=defaults["w_rsi_ma_type"],
                                        clearable=False,
                                    ),
                                ],
                                className="section-card",
                            ),
                            html.Details(
                                [
                                    html.Summary("Entry / Exit"),
                                    html.Label("Trade direction"),
                                    dcc.Dropdown(
                                        id="w_trade_direction",
                                        options=TRADE_DIRECTION_OPTIONS,
                                        value=defaults["w_trade_direction"],
                                        clearable=False,
                                    ),
                                    html.Label("RSI minimum (short entry)"),
                                    dcc.Input(id="w_rsi_min", type="number", value=defaults["w_rsi_min"], min=0, max=100),
                                    html.Label("RSI MA minimum (short entry)"),
                                    dcc.Input(id="w_rsi_ma_min", type="number", value=defaults["w_rsi_ma_min"], min=0, max=100),
                                    html.Label("RSI maximum (long entry)"),
                                    dcc.Input(id="w_rsi_max", type="number", value=defaults["w_rsi_max"], min=0, max=100),
                                    html.Label("RSI MA maximum (long entry)"),
                                    dcc.Input(id="w_rsi_ma_max", type="number", value=defaults["w_rsi_ma_max"], min=0, max=100),
                                    dcc.Checklist(
                                        id="w_use_rsi_relation",
                                        options=[{"label": "Use RSI vs RSI MA", "value": CHECK_ON}],
                                        value=defaults["w_use_rsi_relation"],
                                    ),
                                    html.Label("RSI relation"),
                                    dcc.Dropdown(
                                        id="w_rsi_relation",
                                        options=[{"label": o, "value": o} for o in RSI_RELATION_OPTIONS],
                                        value=defaults["w_rsi_relation"],
                                        clearable=False,
                                    ),
                                    html.Label("Entry band mode"),
                                    dcc.Dropdown(
                                        id="w_entry_band_mode",
                                        options=[{"label": o, "value": o} for o in ENTRY_BAND_OPTIONS],
                                        value=defaults["w_entry_band_mode"],
                                        clearable=False,
                                    ),
                                    html.Label("Exit channel"),
                                    dcc.Dropdown(
                                        id="w_exit_channel",
                                        options=[{"label": o, "value": o} for o in EXIT_CHANNEL_OPTIONS],
                                        value=defaults["w_exit_channel"],
                                        clearable=False,
                                    ),
                                    html.Label("Exit level (short: mid/lower, long: mid/upper)"),
                                    dcc.Dropdown(
                                        id="w_exit_level",
                                        options=[{"label": o, "value": o} for o in EXIT_LEVEL_OPTIONS],
                                        value=defaults["w_exit_level"],
                                        clearable=False,
                                    ),
                                ],
                                className="section-card",
                            ),
                            html.Details(
                                [
                                    html.Summary("Capital & Risk"),
                                    html.Label("Starting cash"),
                                    dcc.Input(id="w_cash", type="number", value=defaults["w_cash"], min=100, max=1_000_000_000, step=100),
                                    html.Label("Commission (fraction)"),
                                    dcc.Input(id="w_commission", type="number", value=defaults["w_commission"], min=0.0, max=0.01, step=0.0001),
                                    html.Label("Trade mode"),
                                    dcc.Dropdown(
                                        id="w_trade_mode",
                                        options=[{"label": o, "value": o} for o in TRADE_MODE_OPTIONS],
                                        value=defaults["w_trade_mode"],
                                        clearable=False,
                                    ),
                                    dcc.Checklist(
                                        id="w_use_stop",
                                        options=[{"label": "Enable stop loss", "value": CHECK_ON}],
                                        value=defaults["w_use_stop"],
                                    ),
                                    html.Label("Stop mode"),
                                    dcc.Dropdown(
                                        id="w_stop_mode",
                                        options=[{"label": o, "value": o} for o in STOP_MODE_OPTIONS],
                                        value=defaults["w_stop_mode"],
                                        clearable=False,
                                    ),
                                    html.Label("Stop %"),
                                    dcc.Input(id="w_stop_pct", type="number", value=defaults["w_stop_pct"], min=0.1, max=20.0, step=0.1),
                                    html.Label("Stop ATR mult"),
                                    dcc.Input(id="w_stop_atr_mult", type="number", value=defaults["w_stop_atr_mult"], min=0.1, max=10.0, step=0.1),
                                    dcc.Checklist(
                                        id="w_use_trailing",
                                        options=[{"label": "Enable trailing stop", "value": CHECK_ON}],
                                        value=defaults["w_use_trailing"],
                                    ),
                                    html.Label("Trail %"),
                                    dcc.Input(id="w_trail_pct", type="number", value=defaults["w_trail_pct"], min=0.1, max=10.0, step=0.1),
                                    html.Label("Max bars in trade"),
                                    dcc.Input(id="w_max_bars_in_trade", type="number", value=defaults["w_max_bars_in_trade"], min=1, max=1000, step=1),
                                    html.Label("Daily loss limit %"),
                                    dcc.Input(id="w_daily_loss_limit", type="number", value=defaults["w_daily_loss_limit"], min=0.0, max=50.0, step=0.5),
                                    html.Label("Risk per trade % of equity"),
                                    dcc.Input(id="w_risk_per_trade_pct", type="number", value=defaults["w_risk_per_trade_pct"], min=0.1, max=100.0, step=0.5),
                                ],
                                className="section-card",
                            ),
                            html.Details(
                                [
                                    html.Summary("Margin Settings"),
                                    html.Label("Max leverage"),
                                    dcc.Input(id="w_max_leverage", type="number", value=defaults["w_max_leverage"], min=1.0, max=125.0, step=0.5),
                                    html.Label("Maintenance margin %"),
                                    dcc.Input(id="w_maintenance_margin_pct", type="number", value=defaults["w_maintenance_margin_pct"], min=0.1, max=50.0, step=0.1),
                                    dcc.Checklist(
                                        id="w_enable_max_margin_util",
                                        options=[{"label": "Limit margin utilization?", "value": CHECK_ON}],
                                        value=defaults["w_enable_max_margin_util"],
                                    ),
                                    html.Label("Max margin utilization %"),
                                    dcc.Input(id="w_max_margin_utilization", type="number", value=defaults["w_max_margin_utilization"], min=10.0, max=100.0, step=5.0),
                                ],
                                className="section-card",
                            ),
                        ],
                        style={
                            "flex": "0 0 320px",
                            "padding": "12px",
                            "border": "1px solid #ddd",
                            "borderRadius": "8px",
                            "maxHeight": "90vh",
                            "overflowY": "auto",
                        },
                        className="sidebar",
                    ),
                    html.Div(
                        [
                            html.Div(id="dirty-warning", style={"marginBottom": "8px", "color": "#b45309"}),
                            dcc.Tabs(
                                id="main-tabs",
                                value="dashboard",
                                children=[
                                    dcc.Tab(
                                        label="Dashboard",
                                        value="dashboard",
                                        children=[
                                            html.Div(id="dashboard-message", style={"margin": "8px 0"}),
                                            html.Div(id="dashboard-metrics", className="metric-grid"),
                                            html.Div(
                                                [
                                                    dcc.Checklist(
                                                        id="show_candles",
                                                        options=[{"label": "Show Candlesticks", "value": CHECK_ON}],
                                                        value=defaults["show_candles"],
                                                    ),
                                                    dcc.Checklist(
                                                        id="lock_rsi_y",
                                                        options=[{"label": "Lock RSI Y-axis (0-100)", "value": CHECK_ON}],
                                                        value=defaults["lock_rsi_y"],
                                                    ),
                                                ],
                                                style={"display": "flex", "gap": "16px", "margin": "8px 0"},
                                            ),
                                            dcc.Loading(
                                                dcc.Graph(id="backtest-figure"),
                                                type="default",
                                            ),
                                        ],
                                    ),
                                    dcc.Tab(
                                        label="Trades & Diagnostics",
                                        value="trades",
                                        children=[
                                            html.Div(id="trades-message", style={"margin": "8px 0"}),
                                            dcc.Loading(
                                                type="default",
                                                children=[
                                                    dash_table.DataTable(
                                                        id="trades-table",
                                                        data=[],
                                                        columns=[],
                                                        row_selectable="single",
                                                        page_size=15,
                                                        sort_action="native",
                                                        filter_action="native",
                                                        style_table={"overflowX": "auto"},
                                                    ),
                                                ],
                                            ),
                                            html.Hr(),
                                            html.Div(id="diagnostics-message", style={"margin": "8px 0"}),
                                            dcc.Loading(
                                                type="default",
                                                children=[
                                                    dash_table.DataTable(
                                                        id="diagnostics-table",
                                                        data=[],
                                                        columns=[],
                                                        page_size=15,
                                                        sort_action="native",
                                                        filter_action="native",
                                                        style_table={"overflowX": "auto", "maxHeight": "400px", "overflowY": "auto"},
                                                    ),
                                                ],
                                            ),
                                            html.Button("Download Diagnostics", id="download-diagnostics-btn", n_clicks=0, className="btn-secondary", style={"marginTop": "8px"}),
                                        ],
                                    ),
                                    dcc.Tab(
                                        label="Analysis & Discovery",
                                        value="analysis",
                                        children=[
                                            dcc.Tabs(
                                                id="analysis-tabs",
                                                value="optimization",
                                                children=[
                                                    dcc.Tab(
                                                        label="Parameter Optimization",
                                                        value="optimization",
                                                        children=[
                                                            html.P(
                                                                "Run a grid search to find optimal parameter combinations."
                                                            ),
                                                            html.Div(
                                                                [
                                                                    html.Div(
                                                                        [
                                                                            html.H4("Parameter Ranges"),
                                                                            html.Label("RSI Minimum Range"),
                                                                            dcc.RangeSlider(
                                                                                id="opt_rsi_range",
                                                                                min=60,
                                                                                max=85,
                                                                                value=[65, 75],
                                                                                step=1,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                            html.Label("Stop Loss Range (%, or ATR mult if stop mode = ATR)"),
                                                                            dcc.RangeSlider(
                                                                                id="opt_stop_range",
                                                                                min=0.5,
                                                                                max=5.0,
                                                                                value=[1.5, 3.0],
                                                                                step=0.5,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                            html.Label("Band Multiplier Range"),
                                                                            dcc.RangeSlider(
                                                                                id="opt_band_range",
                                                                                min=1.5,
                                                                                max=3.0,
                                                                                value=[1.8, 2.2],
                                                                                step=0.1,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                        ],
                                                                        style={"flex": "1", "minWidth": "280px"},
                                                                    ),
                                                                    html.Div(
                                                                        [
                                                                            html.H4("Optimization Settings"),
                                                                            html.Label("Validation mode"),
                                                                            dcc.RadioItems(
                                                                                id="opt_validation_mode",
                                                                                options=[
                                                                                    {"label": "In-sample (single window)", "value": "single"},
                                                                                    {"label": "Walk-forward (train/test)", "value": "walk"},
                                                                                ],
                                                                                value="single",
                                                                            ),
                                                                            html.Label("Optimize for"),
                                                                            dcc.Dropdown(
                                                                                id="opt_metric",
                                                                                options=[
                                                                                    {"label": "profit_factor", "value": "profit_factor"},
                                                                                    {"label": "sharpe_ratio", "value": "sharpe_ratio"},
                                                                                    {"label": "sortino_ratio", "value": "sortino_ratio"},
                                                                                    {"label": "win_rate", "value": "win_rate"},
                                                                                    {"label": "total_equity_return_pct", "value": "total_equity_return_pct"},
                                                                                ],
                                                                                value="profit_factor",
                                                                                clearable=False,
                                                                            ),
                                                                            html.Label("Grid Steps"),
                                                                            dcc.Slider(
                                                                                id="opt_grid_steps",
                                                                                min=2,
                                                                                max=5,
                                                                                value=3,
                                                                                step=1,
                                                                                marks={2: "2", 3: "3", 4: "4", 5: "5"},
                                                                            ),
                                                                            dcc.Checklist(
                                                                                id="opt_include_entry_modes",
                                                                                options=[{"label": "Test all entry band modes", "value": CHECK_ON}],
                                                                                value=_to_checklist(True),
                                                                            ),
                                                                            dcc.Checklist(
                                                                                id="opt_include_exit_levels",
                                                                                options=[{"label": "Test both exit levels", "value": CHECK_ON}],
                                                                                value=[],
                                                                            ),
                                                                            html.Label("Minimum trades required"),
                                                                            dcc.Input(id="opt_min_trades", type="number", value=5, min=1, max=50, step=1),
                                                                            html.H4("Hard Constraints (optional)"),
                                                                            html.Label("Min Profit Factor (0 = off)"),
                                                                            dcc.Input(id="opt_min_pf", type="number", value=0.0, min=0.0, max=10.0, step=0.1),
                                                                            html.Label("Min Win Rate % (0 = off)"),
                                                                            dcc.Input(id="opt_min_wr", type="number", value=0.0, min=0.0, max=100.0, step=1.0),
                                                                            html.Label("Max Drawdown % (0 = off)"),
                                                                            dcc.Input(id="opt_max_dd", type="number", value=0.0, min=0.0, max=100.0, step=1.0),
                                                                            html.Label("Min Total Return % (0 = off)"),
                                                                            dcc.Input(id="opt_min_total_ret", type="number", value=0.0, min=-100.0, max=1000.0, step=1.0),
                                                                            html.Div(
                                                                                [
                                                                                    html.H4("Walk-forward settings"),
                                                                                    html.Label("Train window (days)"),
                                                                                    dcc.Input(id="wf_train_days", type="number", value=180, min=30, max=3650, step=30),
                                                                                    html.Label("Test window (days)"),
                                                                                    dcc.Input(id="wf_test_days", type="number", value=30, min=7, max=365, step=7),
                                                                                    html.Label("Max folds (0 = all)"),
                                                                                    dcc.Input(id="wf_max_folds", type="number", value=8, min=0, max=200, step=1),
                                                                                ],
                                                                                style={"marginTop": "12px"},
                                                                            ),
                                                                        ],
                                                                        style={"flex": "1", "minWidth": "280px"},
                                                                    ),
                                                                ],
                                                                style={"display": "flex", "gap": "24px", "flexWrap": "wrap"},
                                                            ),
                                                            html.Div(id="opt-estimate", style={"margin": "8px 0"}),
                                                            html.Button("Run Optimization", id="opt-run-btn", n_clicks=0, className="btn-primary"),
                                                            dcc.Loading(
                                                                id="loading-optimization",
                                                                type="default",
                                                                children=html.Div(id="opt-status", style={"margin": "8px 0"}),
                                                            ),
                                                            html.H4("Top Configurations"),
                                                            dash_table.DataTable(
                                                                id="opt-results-table",
                                                                data=[],
                                                                columns=[],
                                                                page_size=20,
                                                                sort_action="native",
                                                                filter_action="native",
                                                                style_table={"overflowX": "auto"},
                                                            ),
                                                            html.Div(id="opt-summary", style={"marginTop": "12px"}),
                                                            html.Button("Download Optimization Results", id="opt-download-btn", n_clicks=0, className="btn-secondary", style={"marginTop": "8px"}),
                                                            html.H4("Walk-forward Results"),
                                                            dash_table.DataTable(
                                                                id="wf-results-table",
                                                                data=[],
                                                                columns=[],
                                                                page_size=20,
                                                                sort_action="native",
                                                                filter_action="native",
                                                                style_table={"overflowX": "auto"},
                                                            ),
                                                            html.Div(id="wf-summary", style={"marginTop": "12px"}),
                                                            html.Button("Download Walk-forward Results", id="wf-download-btn", n_clicks=0, className="btn-secondary", style={"marginTop": "8px"}),
                                                        ],
                                                    ),
                                                    dcc.Tab(
                                                        label="Strategy Discovery",
                                                        value="discovery",
                                                        children=[
                                                            html.P(
                                                                "Automatically discover winning strategies by testing parameter combinations."
                                                            ),
                                                            html.Div(
                                                                [
                                                                    html.Div(
                                                                        [
                                                                            html.H4("Performance"),
                                                                            html.Label("Parallel Workers"),
                                                                            dcc.Slider(
                                                                                id="disc_n_workers",
                                                                                min=1,
                                                                                max=max(1, get_cpu_count()),
                                                                                value=max(1, get_cpu_count() - 1),
                                                                                step=1,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                            dcc.Checklist(
                                                                                id="disc_use_parallel",
                                                                                options=[{"label": "Enable Parallel Processing", "value": CHECK_ON}],
                                                                                value=_to_checklist(True),
                                                                            ),
                                                                            dcc.Checklist(
                                                                                id="disc_skip_tested",
                                                                                options=[{"label": "Skip tested combinations", "value": CHECK_ON}],
                                                                                value=_to_checklist(True),
                                                                            ),
                                                                        ],
                                                                        style={"flex": "1", "minWidth": "260px"},
                                                                    ),
                                                                    html.Div(
                                                                        [
                                                                            html.H4("Strategy Parameters"),
                                                                            html.Label("RSI Min Range"),
                                                                            dcc.RangeSlider(
                                                                                id="disc_rsi_range",
                                                                                min=60,
                                                                                max=82,
                                                                                value=[68, 74],
                                                                                step=1,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                            html.Label("RSI MA Min Range"),
                                                                            dcc.RangeSlider(
                                                                                id="disc_rsi_ma_range",
                                                                                min=58,
                                                                                max=80,
                                                                                value=[66, 72],
                                                                                step=1,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                            html.Label("Band Mult Range"),
                                                                            dcc.RangeSlider(
                                                                                id="disc_band_range",
                                                                                min=1.5,
                                                                                max=2.8,
                                                                                value=[1.9, 2.1],
                                                                                step=0.1,
                                                                                tooltip={"placement": "bottom"},
                                                                            ),
                                                                        ],
                                                                        style={"flex": "1", "minWidth": "260px"},
                                                                    ),
                                                                    html.Div(
                                                                        [
                                                                            html.H4("Margin / Risk"),
                                                                            html.Label("Leverage"),
                                                                            dcc.Dropdown(
                                                                                id="disc_leverage_options",
                                                                                options=[{"label": str(v), "value": v} for v in [2.0, 3.0, 5.0, 10.0, 20.0]],
                                                                                value=[2.0, 5.0, 10.0],
                                                                                multi=True,
                                                                            ),
                                                                            html.Label("Risk %"),
                                                                            dcc.Dropdown(
                                                                                id="disc_risk_options",
                                                                                options=[{"label": str(v), "value": v} for v in [0.5, 1.0, 1.5, 2.0, 3.0]],
                                                                                value=[0.5, 1.0, 2.0],
                                                                                multi=True,
                                                                            ),
                                                                            dcc.Checklist(
                                                                                id="disc_include_atr",
                                                                                options=[{"label": "Include ATR Stops", "value": CHECK_ON}],
                                                                                value=_to_checklist(True),
                                                                            ),
                                                                            dcc.Checklist(
                                                                                id="disc_include_trailing",
                                                                                options=[{"label": "Include Trailing", "value": CHECK_ON}],
                                                                                value=_to_checklist(True),
                                                                            ),
                                                                        ],
                                                                        style={"flex": "1", "minWidth": "260px"},
                                                                    ),
                                                                    html.Div(
                                                                        [
                                                                            html.H4("Win Criteria"),
                                                                            html.Label("Min Return %"),
                                                                            dcc.Input(id="disc_min_return", type="number", value=0.0, min=-100.0, max=100.0),
                                                                            html.Label("Max Drawdown %"),
                                                                            dcc.Input(id="disc_max_dd", type="number", value=20.0, min=1.0, max=50.0),
                                                                            html.Label("Min Trades"),
                                                                            dcc.Input(id="disc_min_trades", type="number", value=10, min=5, max=100),
                                                                            html.Label("Min Profit Factor"),
                                                                            dcc.Input(id="disc_min_pf", type="number", value=1.0, min=0.5, max=3.0, step=0.1),
                                                                        ],
                                                                        style={"flex": "1", "minWidth": "240px"},
                                                                    ),
                                                                ],
                                                                style={"display": "flex", "gap": "24px", "flexWrap": "wrap"},
                                                            ),
                                                            html.Div(id="disc-estimate", style={"margin": "8px 0"}),
                                                            html.Button("Run Strategy Discovery", id="disc-run-btn", n_clicks=0, className="btn-primary"),
                                                            dcc.Loading(
                                                                id="loading-discovery",
                                                                type="default",
                                                                children=html.Div(id="disc-status", style={"margin": "8px 0"}),
                                                            ),
                                                            html.Div(id="disc-results", style={"margin": "8px 0"}),
                                                        ],
                                                    ),
                                                    dcc.Tab(
                                                        label="Leaderboard",
                                                        value="leaderboard",
                                                        children=[
                                                            html.H4("Winning Strategies Leaderboard"),
                                                            html.Div(id="lb-stats", style={"display": "flex", "gap": "12px", "flexWrap": "wrap"}),
                                                            html.Div(
                                                                [
                                                                    html.Label("Sort by"),
                                                                    dcc.Dropdown(
                                                                        id="lb_sort_by",
                                                                        options=[
                                                                            {"label": "total_return", "value": "total_return"},
                                                                            {"label": "profit_factor", "value": "profit_factor"},
                                                                            {"label": "sharpe_ratio", "value": "sharpe_ratio"},
                                                                            {"label": "win_rate", "value": "win_rate"},
                                                                            {"label": "max_drawdown", "value": "max_drawdown"},
                                                                        ],
                                                                        value="total_return",
                                                                        clearable=False,
                                                                    ),
                                                                    html.Label("Show top"),
                                                                    dcc.Dropdown(
                                                                        id="lb_top_n",
                                                                        options=[{"label": str(v), "value": v} for v in [10, 25, 50, 100]],
                                                                        value=10,
                                                                        clearable=False,
                                                                    ),
                                                            html.Button("Refresh", id="lb-refresh-btn", n_clicks=0, className="btn-secondary"),
                                                                ],
                                                                style={"display": "flex", "gap": "12px", "alignItems": "center"},
                                                            ),
                                                            dcc.Loading(
                                                                id="loading-leaderboard",
                                                                type="default",
                                                                children=html.Div(id="lb-status", style={"margin": "8px 0"}),
                                                            ),
                                                            html.Div(id="lb-updated", style={"margin": "8px 0", "fontSize": "12px"}),
                                                            dcc.Loading(
                                                                id="loading-leaderboard-table",
                                                                type="default",
                                                                children=html.Div([
                                                                    dash_table.DataTable(
                                                                        id="lb-table",
                                                                        data=[],
                                                                        columns=[],
                                                                        row_selectable="single",
                                                                        page_size=15,
                                                                        sort_action="native",
                                                                        filter_action="native",
                                                                        style_table={"overflowX": "auto"},
                                                                        hidden_columns=["FullHash", "ParamsJson"],
                                                                    ),
                                                                    html.Div(id="lb-details", style={"marginTop": "12px"}),
                                                                ]),
                                                            ),
                                                            html.Button("Load This Strategy", id="lb-load-btn", n_clicks=0, className="btn-primary"),
                                                            html.Button("Export Leaderboard CSV", id="lb-download-btn", n_clicks=0, className="btn-secondary", style={"marginLeft": "8px"}),
                                                        ],
                                                    ),
                                                    dcc.Tab(
                                                        label="Pattern Recognition",
                                                        value="patterns",
                                                        children=[
                                                            html.H4("Discovered Patterns & Rules"),
                                                            html.Button("Analyze Patterns", id="patterns-btn", n_clicks=0, className="btn-primary"),
                                                            dcc.Loading(
                                                                id="loading-patterns",
                                                                type="default",
                                                                children=html.Div(id="patterns-status", style={"margin": "8px 0"}),
                                                            ),
                                                            dcc.Loading(
                                                                id="loading-patterns-summary",
                                                                type="default",
                                                                children=dcc.Markdown(id="patterns-summary"),
                                                            ),
                                                        ],
                                                    ),
                                                    dcc.Tab(
                                                        label="Job Queue",
                                                        value="jobs",
                                                        children=[
                                                            html.H4("Background Job Queue"),
                                                            html.Div(
                                                                [
                                                                    html.Label("Status"),
                                                                    dcc.Dropdown(
                                                                        id="jobs-status-filter",
                                                                        options=[
                                                                            {"label": "all", "value": "all"},
                                                                            {"label": "queued", "value": "queued"},
                                                                            {"label": "running", "value": "running"},
                                                                            {"label": "succeeded", "value": "succeeded"},
                                                                            {"label": "failed", "value": "failed"},
                                                                            {"label": "canceled", "value": "canceled"},
                                                                        ],
                                                                        value="all",
                                                                        clearable=False,
                                                                        style={"minWidth": "160px"},
                                                                    ),
                                                                    html.Label("Type"),
                                                                    dcc.Dropdown(
                                                                        id="jobs-type-filter",
                                                                        options=[
                                                                            {"label": "all", "value": "all"},
                                                                            {"label": "optimize", "value": "optimize"},
                                                                            {"label": "discover", "value": "discover"},
                                                                            {"label": "leaderboard_refresh", "value": "leaderboard_refresh"},
                                                                            {"label": "patterns_refresh", "value": "patterns_refresh"},
                                                                            {"label": "prices_ingest", "value": "prices_ingest"},
                                                                        ],
                                                                        value="all",
                                                                        clearable=False,
                                                                        style={"minWidth": "220px"},
                                                                    ),
                                                                    html.Label("Limit"),
                                                                    dcc.Dropdown(
                                                                        id="jobs-limit",
                                                                        options=[{"label": str(v), "value": v} for v in [25, 50, 100, 200]],
                                                                        value=50,
                                                                        clearable=False,
                                                                        style={"minWidth": "120px"},
                                                                    ),
                                                                    dcc.Checklist(
                                                                        id="jobs-auto-refresh",
                                                                        options=[{"label": "Auto-refresh", "value": CHECK_ON}],
                                                                        value=_to_checklist(True),
                                                                        style={"marginTop": "22px"},
                                                                    ),
                                                                    html.Button(
                                                                        "Refresh",
                                                                        id="jobs-refresh-btn",
                                                                        n_clicks=0,
                                                                        className="btn-secondary",
                                                                        style={"marginTop": "22px"},
                                                                    ),
                                                                ],
                                                                style={"display": "flex", "gap": "12px", "alignItems": "center", "flexWrap": "wrap"},
                                                            ),
                                                            dcc.Loading(
                                                                id="loading-jobs-status",
                                                                type="default",
                                                                children=html.Div(id="jobs-status", style={"margin": "8px 0"}),
                                                            ),
                                                            html.H5("Workers"),
                                                            html.Div(id="workers-summary", style={"margin": "8px 0"}),
                                                            dcc.Loading(
                                                                id="loading-jobs-tables",
                                                                type="default",
                                                                children=html.Div([
                                                                    dash_table.DataTable(
                                                                        id="workers-table",
                                                                        data=[],
                                                                        columns=[],
                                                                        page_size=8,
                                                                        sort_action="native",
                                                                        style_table={"overflowX": "auto"},
                                                                    ),
                                                                    dash_table.DataTable(
                                                                        id="jobs-table",
                                                                        data=[],
                                                                        columns=[],
                                                                        row_selectable="single",
                                                                        page_size=15,
                                                                        sort_action="native",
                                                                        filter_action="native",
                                                                        style_table={"overflowX": "auto"},
                                                                    ),
                                                                ]),
                                                            ),
                                                            html.Hr(),
                                                            html.Div(
                                                                [
                                                                    html.Button("Refresh Details", id="jobs-detail-refresh-btn", n_clicks=0, className="btn-secondary"),
                                                                    html.Button(
                                                                        "Cancel Selected",
                                                                        id="jobs-cancel-btn",
                                                                        n_clicks=0,
                                                                        className="btn-secondary",
                                                                        style={"marginLeft": "8px"},
                                                                    ),
                                                                ],
                                                                style={"display": "flex", "alignItems": "center"},
                                                            ),
                                                            dcc.Loading(
                                                                id="loading-job-details",
                                                                type="default",
                                                                children=html.Div([
                                                                    html.Div(id="jobs-detail-status", style={"margin": "8px 0"}),
                                                                    html.Div(id="jobs-detail-summary", style={"margin": "8px 0", "fontSize": "12px"}),
                                                                    dcc.Markdown(id="jobs-detail-json"),
                                                                    html.H4("Events"),
                                                                    dash_table.DataTable(
                                                                        id="jobs-events-table",
                                                                        data=[],
                                                                        columns=[],
                                                                        page_size=10,
                                                                        sort_action="native",
                                                                        style_table={"overflowX": "auto", "maxHeight": "260px", "overflowY": "auto"},
                                                                    ),
                                                                ]),
                                                            ),
                                                        ],
                                                    ),
                                                ],
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                        ],
                        style={"flex": "1", "padding": "12px"},
                        className="main-panel",
                    ),
                ],
                style={"display": "flex", "gap": "16px"},
                className="app-shell",
            ),
        ],
        style={"padding": "16px"},
        className="app-root",
        id="app-root",
    )
